// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"grpcserver/data/ent/userentity"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserEntityCreate is the builder for creating a UserEntity entity.
type UserEntityCreate struct {
	config
	mutation *UserEntityMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (uec *UserEntityCreate) SetUsername(s string) *UserEntityCreate {
	uec.mutation.SetUsername(s)
	return uec
}

// SetPassword sets the "password" field.
func (uec *UserEntityCreate) SetPassword(s string) *UserEntityCreate {
	uec.mutation.SetPassword(s)
	return uec
}

// Mutation returns the UserEntityMutation object of the builder.
func (uec *UserEntityCreate) Mutation() *UserEntityMutation {
	return uec.mutation
}

// Save creates the UserEntity in the database.
func (uec *UserEntityCreate) Save(ctx context.Context) (*UserEntity, error) {
	return withHooks(ctx, uec.sqlSave, uec.mutation, uec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uec *UserEntityCreate) SaveX(ctx context.Context) *UserEntity {
	v, err := uec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uec *UserEntityCreate) Exec(ctx context.Context) error {
	_, err := uec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uec *UserEntityCreate) ExecX(ctx context.Context) {
	if err := uec.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uec *UserEntityCreate) check() error {
	if _, ok := uec.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "UserEntity.username"`)}
	}
	if _, ok := uec.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "UserEntity.password"`)}
	}
	return nil
}

func (uec *UserEntityCreate) sqlSave(ctx context.Context) (*UserEntity, error) {
	if err := uec.check(); err != nil {
		return nil, err
	}
	_node, _spec := uec.createSpec()
	if err := sqlgraph.CreateNode(ctx, uec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uec.mutation.id = &_node.ID
	uec.mutation.done = true
	return _node, nil
}

func (uec *UserEntityCreate) createSpec() (*UserEntity, *sqlgraph.CreateSpec) {
	var (
		_node = &UserEntity{config: uec.config}
		_spec = sqlgraph.NewCreateSpec(userentity.Table, sqlgraph.NewFieldSpec(userentity.FieldID, field.TypeInt))
	)
	if value, ok := uec.mutation.Username(); ok {
		_spec.SetField(userentity.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := uec.mutation.Password(); ok {
		_spec.SetField(userentity.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	return _node, _spec
}

// UserEntityCreateBulk is the builder for creating many UserEntity entities in bulk.
type UserEntityCreateBulk struct {
	config
	err      error
	builders []*UserEntityCreate
}

// Save creates the UserEntity entities in the database.
func (uecb *UserEntityCreateBulk) Save(ctx context.Context) ([]*UserEntity, error) {
	if uecb.err != nil {
		return nil, uecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uecb.builders))
	nodes := make([]*UserEntity, len(uecb.builders))
	mutators := make([]Mutator, len(uecb.builders))
	for i := range uecb.builders {
		func(i int, root context.Context) {
			builder := uecb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserEntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uecb *UserEntityCreateBulk) SaveX(ctx context.Context) []*UserEntity {
	v, err := uecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uecb *UserEntityCreateBulk) Exec(ctx context.Context) error {
	_, err := uecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uecb *UserEntityCreateBulk) ExecX(ctx context.Context) {
	if err := uecb.Exec(ctx); err != nil {
		panic(err)
	}
}
